# Generated by Django 5.2.10 on 2026-01-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatsession_chatmessage_codesnippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('Customer', 'customer')], default='Customer', max_length=20),
        ),
    ]
