# Generated by Django 5.2.10 on 2026-02-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking the user', null=True),
        ),
    ]
